suod: required
services:
  - docker

before_install:
  - docker build -t zezenk/docker-multi -f ./client/Dockerfile.dev ./client
  # - docker build myotherproject

script:
  - docker run -e CI=true zezenk/docker-multi npm run test
  # - docker run myotherproject run test

# build the images and push them to Docker Hub
after_success:
  - docker build -t zezenk/docker-client ./client
  - docker build -t zezenk/docker-nginx ./nginx
  - docker build -t zezenk/docker-server ./server
  - docker build -t zezenk/docker-worker ./worker
  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
  # Push to Docker Hub
  - docker push zezenk/docker-client
  - docker push zezenk/docker-nginx
  - docker push zezenk/docker-server
  - docker push zezenk/docker-worker

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker-multi"
  env: "DockerMulti-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-498093216196"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
